plugin: amazon.aws.aws_ec2
regions:
  - ap-northeast-2

filters:
  "tag:Project": "monitoring"   # 너 프로젝트 태그에 맞춰 변경
  "instance-state-name": "running"

keyed_groups:
  - key: tags.role
    prefix: role

compose:
  ansible_host: public_ip_address
