global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # (1) Node Exporter (9100): service + asg
  - job_name: node
    ec2_sd_configs:
      - region: ap-northeast-2
        port: 9100
        filters:
          - name: tag:role
            values: ["asg", "service"]
          - name: instance-state-name
            values: ["running"]
    relabel_configs:
      - source_labels: [__meta_ec2_tag_role]
        target_label: role
      - source_labels: [__meta_ec2_private_ip]
        target_label: private_ip
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id
      - source_labels: [__meta_ec2_tag_Name]
        target_label: name

  # (2) Node App metrics (8080): service + asg
  - job_name: nodeapp
    metrics_path: /metrics
    ec2_sd_configs:
      - region: ap-northeast-2
        port: 8080
        filters:
          - name: tag:role
            values: ["asg", "service"]
          - name: instance-state-name
            values: ["running"]
    relabel_configs:
      - source_labels: [__meta_ec2_tag_role]
        target_label: role
      - source_labels: [__meta_ec2_private_ip]
        target_label: private_ip
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id
      - source_labels: [__meta_ec2_tag_Name]
        target_label: name
