{
 "title": "dashboard_temp",
 "description": "test1",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "1.1.RPS by Target Instances",
   "type": "timeseries",
   "description": "A graph showing whether ALB traffic is distributed across ASG instances.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance, role) (\r\n  rate(http_requests_total{job=\"nodeapp\", role=~\"asg|service\"}[$__rate_interval])\r\n)\r\n",
     "legendFormat": "{{role}} - {{instance}}"
    }
   ]
  },
  {
   "title": "1.2.Total RPS",
   "type": "timeseries",
   "description": "Graph showing total RPS\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(\r\n  rate(http_requests_total{job=\"nodeapp\", role=~\"asg|service\"}[$__rate_interval])\r\n)\r\n",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "2-1.Target instance UP/DOWN",
   "type": "stat",
   "description": "Graph showing whether target instance is up/down",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) (up{job=\"nodeapp\", role=\"asg\"})\r\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "2-2.Num of alive target",
   "type": "stat",
   "description": "graph showing number of alive target",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (instance) (up{job=\"nodeapp\", role=\"asg\"}))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3.1.Node exporter Up count",
   "type": "timeseries",
   "description": "graph Proving that instances have actually scaled out/in by “logarithmic change”",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(up{job=\"node\", role=\"asg\"})\r\n",
     "legendFormat": "UP count"
    }
   ]
  },
  {
   "title": "3-2. CPU usage by instance (%)",
   "type": "timeseries",
   "description": "graph showing Scaling load basis",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance, role) (\r\n  rate(node_cpu_seconds_total{job=\"node\", mode=\"idle\", role=~\"service|asg\"}[5m])\r\n))\r\n",
     "legendFormat": "{{role}} - {{instance}}"
    }
   ]
  },
  {
   "title": " 3-3. Memory usage by instance (%)",
   "type": "timeseries",
   "description": "Graphs to support resource pressure/scaling rationale",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 24 },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{job=\"node\", role=~\"asg|service\"} / node_memory_MemTotal_bytes{job=\"node\", role=~\"asg|service\"}))\r\n",
     "legendFormat": "{{role}} - {{instance}}"
    }
   ]
  },
  {
   "title": "4-1. HTTP  Error Rate(5xx+4xx) (%)",
   "type": "timeseries",
   "description": "Graph showing whether increasing traffic does not increase failures/errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "100 *\r\nsum(rate(http_requests_total{job=\"nodeapp\", role=~\"asg|service\", status=~\"4..\"}[$__rate_interval]))\r\n/\r\nclamp_min(\r\n  sum(rate(http_requests_total{job=\"nodeapp\", role=~\"asg|service\"}[$__rate_interval])),\r\n  0.001\r\n)\r\n",
     "legendFormat": "4xx"
    },
    {
     "expr": "100 *\r\nsum(rate(http_requests_total{job=\"nodeapp\", role=~\"asg|service\", status=~\"5..\"}[$__rate_interval]))\r\n/\r\nclamp_min(\r\n  sum(rate(http_requests_total{job=\"nodeapp\", role=~\"asg|service\"}[$__rate_interval])),\r\n  0.001\r\n)\r\n",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "4.2.Success rate(2xx/3xx) (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "100 *\r\nsum(rate(http_requests_total{job=\"nodeapp\", role=~\"asg|service\", status=~\"[23]..\"}[$__rate_interval]))\r\n/\r\nclamp_min(\r\n  sum(rate(http_requests_total{job=\"nodeapp\", role=~\"asg|service\"}[$__rate_interval])),\r\n  0.001\r\n)\r\n",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "4-3. Error Composition (4xx vs 5xx) (%)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum(increase(http_requests_total{job=\"nodeapp\", role=~\"asg|service\", status=~\"4..\"}[$__range]))\r\n/\r\nclamp_min(\r\n  sum(increase(http_requests_total{job=\"nodeapp\", role=~\"asg|service\", status=~\"[45]..\"}[$__range])),\r\n  1\r\n)\r\n",
     "legendFormat": "4xx"
    },
    {
     "expr": "100 *\r\nsum(increase(http_requests_total{job=\"nodeapp\", role=~\"asg|service\", status=~\"5..\"}[$__range]))\r\n/\r\nclamp_min(\r\n  sum(increase(http_requests_total{job=\"nodeapp\", role=~\"asg|service\", status=~\"[45]..\"}[$__range])),\r\n  1\r\n)\r\n",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "5.1.Response time p95 (total/route)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, route) (\r\n    rate(http_request_duration_seconds_bucket{\r\n      job=\"nodeapp\",\r\n      role=~\"asg|service\",\r\n      route=~\"^(/|/health|/work|/kill|/fail|/unavailable|/metrics)$\"\r\n    }[$__rate_interval])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5.2.Response time p95(instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, instance, role) (\r\n    rate(http_request_duration_seconds_bucket{job=\"nodeapp\", role=~\"asg|service\"}[$__rate_interval])\r\n  )\r\n)\r\n",
     "legendFormat": "{{role}} - {{instance}}"
    }
   ]
  }
 ]
}