---
project_dir: /home/ubuntu/monitoring

# docker compose 실행에 사용할 프로젝트 경로(레포가 /opt/monitoring 에 클론되니 심볼릭으로 맞추거나)
repo_dir: /opt/monitoring

# node exporter
node_exporter_port: 9100

# app
app_port: 8080

# monitoring
grafana_port: 3000
prometheus_port: 9090
