repo_url: "https://github.com/ktcloudmini/monitoring.git"
app_dir: "/home/ubuntu/monitoring"

# 각 role별로 올릴 compose profile
compose_profiles:
  monitoring: ["monitoring"]
  service: ["app", "node"]
  asg: ["app", "node"]

# docker compose project name (충돌 방지용)
compose_project: "monitoring"
