---
- name: Deploy Prometheus + Grafana on monitoring instance
  hosts: monitoring
  become: true
  roles:
    - common
    - deploy_stack
    - prometheus_config
  vars:
    compose_profiles_csv: "monitoring"
